# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: default

channels:
  - conda-forge

dependencies:
  - python=3.9
  - ansible
  - terraform
  - certbot
  - vault
  - python-openstackclient
  - gh
  - shyaml
  - pip
  - maturin
  - rust
  - just
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pytest-regressions
  - matplotlib
  - ansible-kernel
  - jupytext
  - pre-commit
  - zsh
  - ablog
  - numpydoc
  - sphinx
  - altair
  - vega_datasets
  - jupyterlab
  - jupyterlab-git
  - matplotlib
  - geopandas
  - geojson
  - pysal
  - mapclassify
  - osmnx
  - pyrosm
  - geopy
  - geojson
  - rasterio
  - contextily
  - folium
  - mplleaflet
  - bokeh
  - pip
  - pandas
  - conda-merge


  - pip:
    - ovh
    - certbot-dns-ovh
    - jupyterlite[all]
    - jupyterlite-sphinx
    - myst-parser
    - myst-nb
    - sphinx-theme-pd
    - pydata-sphinx-theme
    - sphinxcontrib-mermaid
    - bqplot
    - jupyter-book
    - zsh_jupyter_kernel
    - sphinx-ansible
    - sphinx-terraform
    - sshkernel
    - ghp-import
    - nbgitpuller
    - sphinx-comments
    - sphinx-book-theme
    - sphinxcontrib-youtube
    - sphinx-design
    - sphinx-comments
    - sphinx-tabs
    - sphinxext-opengraph
    - sphinx-thebe
    - sphinx-togglebutton
    - ipywidgets
    - nbclient
    - plotly
    - sphinxcontrib-bibtex
    - beautifulsoup4
    - coverage
