# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: default

channels:
  - conda-forge

dependencies:
  - python=3.9
  - ansible
  - terraform
  - certbot
  - vault
  - python-openstackclient
  - gh
  - shyaml
  - pip
  - maturin
  - rust
  - just
  - pytest
  - pytest-benchmark
  - pytest-cov
  - pytest-regressions
  - cffi
  - virtualenv
  - auditwheel
  - matplotlib
  - ansible-kernel
  - jupytext
  - pre-commit
  - zsh
  - ablog
  - numpydoc
  - sphinx
  - altair
  - vega_datasets
  - jupyterlab
  - jupyterlab-git
  - matplotlib
  - geopandas
  - geojson
  - pysal
  - mapclassify
  - osmnx
  - pyrosm
  - geopy
  - geojson
  - rasterio
  - contextily
  - folium
  - mplleaflet
  - bokeh
  - pandas
  - conda-merge
  - tox
  - tox-conda
  - poetry
  - twine
  - nodejs ==16.13.2
  - ipyleaflet
  - xeus-python
  - conda-smithy
  - clang
  - lld
  - llvm
  - llvm-tools
  - llvmdev
  - grayskull
  - zig
  - testinfra
  - pytest-testinfra
  - consul
  - consul-template
  - go
  - passlib
  - dotnet-sdk
  - six
  - fastapi
  - uvicorn[standard]
  - python-multipart
  - mamba
  - pip
  - fastapi
  - typer
  - authlib=0.15.5
  - psycopg2
  - httpx=0.20.0
  - sqlalchemy
  - sqlalchemy-utils
  - sqlite
  - python-multipart
  - uvicorn
  - zstandard
  - conda-build
  - appdirs
  - toml
  - fsspec
  - requests
  - h2
  - pluggy
  - jinja2
  - itsdangerous
  - alembic
  - zchunk
  - s3fs
  - gcsfs >=2022.03
  - sphinx
  - sphinx-book-theme
  - tenacity
  - xattr
  - aiofiles
  - pyyaml
  - ujson
  - prometheus_client
  - pamela
  - typing_extensions
  - adlfs
  - importlib_metadata

  - pip:
    - ovh
    - certbot-dns-ovh
    - certbot-dns-cloudflare
    - jupyterlite[all]
    - jupyterlite-sphinx
    - myst-parser
    - myst-nb
    - sphinx-theme-pd
    - pydata-sphinx-theme
    - sphinxcontrib-mermaid
    - bqplot
    - zsh_jupyter_kernel
    - sphinx-ansible
    - sphinx-terraform
    - sshkernel
    - ghp-import
    - nbgitpuller
    - sphinx-comments
    - sphinxcontrib-youtube
    - sphinx-design
    - sphinx-comments
    - sphinx-tabs
    - sphinxext-opengraph
    - sphinx-thebe
    - sphinx-togglebutton
    - ipywidgets
    - nbclient
    - plotly
    - sphinxcontrib-bibtex
    - beautifulsoup4
    - coverage
    - sphinx-gallery
    - sphinxcontrib-images
    - sphinxawesome-theme
    - sphinx-theme-builder[cli]
    - yamllint
    - ansible-lint
    - molecule
    - pdoc
    - PyPortfolioOpt
#    - git+https://github.com/QuantEcon/quantecon-book-theme.git
#    - git+https://github.com:dorgeln/sphinx-book-theme.git
#    - sphinx-book-theme
